### ISSUE TITLE
Add support for the .github repository

### ISSUE THREAD

**Issue by glennawatson** [toolmantim/release-drafter#150]
Hi there,

Thanks for making this fantastic tool, definitely much appreciated.

So one feature that github added recently was a global .github repository which would allow templates for your entire organization https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

One thing that would be great since our github organisation with 8 different active projects is to have only one 'release-drafter.yml' file using that repository.

Maybe it'd be possible to look up to see if that file exists in that .github repository and use that if one doesn't exist in the current repository?

**Comment by toolmantim** [comment]
That's a great question, and luckily I think we already have support for something like that.

It's in the readme, but perhaps it should be its own section? It's probably easy to miss!

> Release Drafter also supports [Probot Config](https://github.com/probot/probot-config), if you want to store your configuration files in a central repository. This allows you to share configurations between projects, and create a organization-wide configuration file by creating a repository named .github with the file .github/release-drafter.yml.

Also I must admit, that Probot Config readme isn't very user friendly at all. But it should work exactly how you describe.

Want to give it a go and let me know if it works for you?

**Comment by glennawatson** [comment]
Sure, I'll give it a shot. Thanks for the help. Will reply once I see how it goes here (and probably close)

**Comment by glennawatson** [comment]
Yep, this seems to do the trick. thanks

**Comment by toolmantim** [comment]
🎉
