### ISSUE TITLE
non-semver next version?

### ISSUE THREAD

**Issue by casz** [toolmantim/release-drafter#156]
Would you be interested in supporting non-semver next version?

I know it is not much to change the name but selecting the right tag can be a little cumbersome.

Would love to contribute the work, if you'd be interested.

**Comment by toolmantim** [comment]
Thanks for the question! Sounds like a good thing to support, but I’m not entirely sure what you’re describing? Could you give a config example, and resulting release draft? Thanks!

**Comment by casz** [comment]
Yes, that's my bad for not including an example and describe exactly what it is I am asking for :)
https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/.github/release-drafter.yml

We would like to have `tag-template: configuration-as-code-$NEXT_MINOR_VERSION` 
be only `major.minor` version numbered instead of `major.minor.patch`

In bash, it would be done with something like `${NEXT_MINOR_VERSION%.*}` removing on the first match to the left :sweat_smile:

**Comment by toolmantim** [comment]
Thanks for the details! Is that because you don’t do patch versions?

Thinking about ideas, perhaps `patch_versions: false`?

**Comment by casz** [comment]
yes, maven convention often has no patch_version 😄

I could change the version numbers 🤷‍♂️ Others might have the same need.

`patch_versions: false` sounds helpful to me!

I can send the PR later today. 😅

**Comment by toolmantim** [comment]
Cool, I think a `patch_versions` option sounds like a plan. And a PR would be much appreciated, thanks!

**Comment by TimonVS** [comment]
While I do think this is a nice addition, can we make it a bit more generic so that it will also work for users who just want to have v1, v2 etc.? I can see users asking for that next and it would be a bit annoying to have to add another option for that :)

We could add an option called `version-template` or `version-format` maybe? E.g.:

```yml
version-template: <%= major %>.<%= minor %>
```

We could use Lodash [`_.template`](https://lodash.com/docs/4.17.11#template) to make this work:

```js
const _ = require('lodash')

const compiled = _.template('<%= major %>.<%= minor %>')
compiled({ major: 1, minor: 0, patch: 1 }) //> 1.1
```

**Comment by casz** [comment]
@TimonVS I like your suggestion!

if @toolmantim agrees I'll see what I can work out!

**Comment by toolmantim** [comment]
That’s a good point @TimonVS.

What if it were `version-template` and we used the same `$` template pattern we use for everything else, rather than lodash?

**Comment by casz** [comment]
@TimonVS if I were to use version-template I would use as the norm. So the default version template would be

You can override the settings template settings for lodash template, I would properly use the 
```
version-template: $major.$minor.$patch
```

You achieve this with
```
var compiled = _.template('$major.$minor.$patch', { interpolate: /\$([a-zA-Z]+)/g })
```

**Comment by casz** [comment]
Ah, @toolmantim was faster than me, I was writing template settings. 😅

**Comment by casz** [comment]
we could properly set the template to only allow major,minor,patch :)

**Comment by toolmantim** [comment]
I don’t mind much either way, but if you see `lib/releases.rb` you’ll see we use simple `.replace()` calls?

**Comment by casz** [comment]
we can use replace for sure 😅

**Comment by casz** [comment]
> `lib/releases.rb`

When did we switch to ruby :trollface: 🤣
