### ISSUE TITLE
Allow custom user templating?

### ISSUE THREAD

**Issue by casz** [toolmantim/release-drafter#168]
Would be nice to give the user some templating power.

For instance, I need a regex capturing of `JENKINS-\d+` like `JENKINS-123` and turn it into a Markdown link of `[JENKINS-123](https://issues.jenkins-ci.org/browse/JENKINS-123)` [JENKINS-123](https://issues.jenkins-ci.org/browse/JENKINS-123)

Would be possible to add once #161 is merged.

The user templating would be run last.

**Comment by halkeye** [comment]
are you tackling this? it seems #161 is merged. Otherwise I might be interested in trying

**Comment by casz** [comment]
Go ahead

**Comment by TimonVS** [comment]
Looks like this has been resolved in #185 😄
