### ISSUE TITLE
Open PRs on new repos with default config

### ISSUE THREAD

**Issue by abraham** [toolmantim/release-drafter#18]
I just enabled Release Drafter on a couple of repos and thought it was broken for a while before remembering that it requires also adding a template. It would be great if when adding access to a new repo that doesn't have a template that a PR would be opened adding the default template.

This is something that Renovate does and it's fantastic. https://github.com/abraham/remotedata/pull/1

**Comment by toolmantim** [comment]
Thanks! I love that functionality in Renovate. 

I haven’t looked into what publishing a branch and PR via the [OctoKit JS API](https://octokit.github.io/rest.js/) would entail, but it’s something I’d love to see added.

**Comment by balloob** [comment]
Why even depend on a config file to consider being enabled at all? As an org owner I can enable it per repo. If it's enabled, just use a default config if no config file found.

**Comment by toolmantim** [comment]
I've been thinking about this a bit — it's something I'd like to support. The only problem with just going and creating draft releases without a config is that you can create a real mess if you install the GitHub App org wide.

But I think there's another neat way to support this, which came with with the v0.0.2 release of [probot-config](https://github.com/probot/probot-config) which Release Drafter uses. And if it does work, I'll have to add it to the readme here.

If you create a `.github` repo in your GitHub org, and put your `release-drafter.yml` file in that repo, it'll be used for all the repos in your org without even needing to add a config to each one.

And each repo can override the default config via its `.github/release-drafter.yml` file.

The probot-config readme isn't great sorry, but if you wanted to give it a go and report back, then I'll update the readme and maybe that's enough?

I still like the idea of creating a PR with the config though 🤔
