### ISSUE TITLE
associatedPullRequests and graphql with local deployment

### ISSUE THREAD

**Issue by bag0bits** [toolmantim/release-drafter#234]
I was trying to deploy this locally but I keep running in to this schema problem.  I think it's because it's missing "@octokit/graphql-schema" but I'm not too sure. I think I installed the module but it's still getting the same error.  Have you guys seen this with a local deployment?

> 02:57:01.336Z ERROR event: Field 'associatedPullRequests' doesn't exist on type 'Commit' (id=ea30ddf8-8d86-11e9-959c-37e2eb14684d)
  GraphqlError: Field 'associatedPullRequests' doesn't exist on type 'Commit'
      at request.then.response (/app/node_modules/@octokit/graphql/lib/graphql.js:31:15)

**Comment by bag0bits** [comment]
I think I've track this down to the error is coming from our GitHub Enterprise server.  Maybe it's not at parity with GitHub.com's API schema version?

**Comment by casz** [comment]
Most likely this was only added recently like within the last few months.
See: https://github.community/t5/GitHub-API-Development-and/Get-pull-request-associated-with-a-commit/m-p/20305/highlight/true#M1100

**Comment by bag0bits** [comment]
yeah found that eventually.. thanks for the reply.

**Comment by jonbrohauge** [comment]
@bag0bits If you can upgrade your GHE to 2.17.4 this is no longer an issue.
