### ISSUE TITLE
PRs that only have the repository as a source are shown in changelogs

### ISSUE THREAD

**Issue by manuel-hegner** [toolmantim/release-drafter#258]
Our changelog shows PRs from our repo into a fork. This is especially annoying since https://github.com/apps/pull is used to keep the forks up to date which creates a lot of those PRs. The link to those PRs is also wrong, since it uses the right id but the wrong repo.

So in `bakdata/conquery` you can see
![image](https://user-images.githubusercontent.com/12272732/61211249-69002800-a6ff-11e9-97b2-791dc2845095.png)
while these PRs are actually in a fork, e.g.
![image](https://user-images.githubusercontent.com/12272732/61211303-8b924100-a6ff-11e9-81e9-16004b436fae.png)

**Comment by v00d00** [comment]
This should be solved by #251 I think

**Comment by manuel-hegner** [comment]
Oh yeah, awesome.
