### ISSUE TITLE
May I use this tool for my local repository?

### ISSUE THREAD

**Issue by duckscofield** [toolmantim/release-drafter#27]
My projects are not on Github. They are in internal company because of policy. I feel this is great tool, but if it could install locally will be better.

**Comment by toolmantim** [comment]
Hey @duckscofield. Thanks! It's a good question. You can't run this locally, and it's probably out of the scope of this particular project.

Maybe one of the other ones on npm could help? https://www.npmjs.com/search?q=release%20notes

If you find something that's suitable, let me know!
