### ISSUE TITLE
Recent releases are unverified

### ISSUE THREAD

**Issue by Remzi1993** [toolmantim/release-drafter#314]
Dear Sir or Madam,

Recent releases made with Release Drafter end up [unverified](https://help.github.com/en/articles/checking-your-commit-and-tag-signature-verification-status). See images below:
![Screenshot from 2019-10-13 18-11-40](https://user-images.githubusercontent.com/980950/66718648-76a07900-ede6-11e9-87f7-039ca9166c94.png)
See situation before, the releases were verified, see image below
![Screenshot from 2019-10-13 18-12-17](https://user-images.githubusercontent.com/980950/66718655-7c965a00-ede6-11e9-94bc-5f8065f5ac27.png)

I hope we could solve this issue together, it seems like your GPG key is either not uploaded or expired.

Kind regards,
Remzi

EDIT: See repo: https://github.com/Remzi1993/jquery-manager/releases

**Comment by casz** [comment]
This has nothing to do with release drafter and everything to do with your GPG signature on the tag.

**Comment by casz** [comment]
Check your commits: https://github.com/Remzi1993/jquery-manager/commits/master

**Comment by Remzi1993** [comment]
@casz Oops, you're right. I deleted an old GPG key from an old PC. I think the next time around I will copy and move my key to a new PC. I'm very sorry for open wrongfully a new issue.
