### ISSUE TITLE
associatedPullRequests empty when Pull Request merged in Github Enterprise 2.18.5

### ISSUE THREAD

**Issue by Sciwiman** [toolmantim/release-drafter#322]
Have noticed a bizarre timing issue when interacting with the GHE (2.18.5) GraphQL API.

When the release drafter is executed following a merged pull request, the associatedPullRequests on the latest commit is empty.

As a result, when a pull request is merged into master the release notes are not updated with the latest pull request.

A quick (hack) fix was to add a one second delay at the top of [lib/commit.js](https://github.com/toolmantim/release-drafter/blob/master/lib/commits.js). This is not an ideal solution, but was something to get it up and running in my current environment

Has anyone else experienced a similar issue with GHE?

**Comment by TimonVS** [comment]
Thanks for reporting @Sciwiman. I personally don't use GHE so I haven't experienced the issue. It seems to me that this is an issue on GitHub's end though. Would you mind reporting it to them? :)

**Comment by Sciwiman** [comment]
Thanks @TimonVS - Will create a support ticket with the GHE team.
