### ISSUE TITLE
No valid config found

### ISSUE THREAD

**Issue by pratyushbansal** [toolmantim/release-drafter#328]
Hi,

I have added the required yml files, but on running the action it gives the error -
INFO probot: <repo name>: No valid config found
Please help

release-drafter.yml

branches:
  - ordering_intial_master
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'core'
template: |
  ## Changes
  $CHANGES

release-management.yml

name: Release Management

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - ordering_intial_master

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: toolmantim/release-drafter@v5.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

**Comment by casz** [comment]
Link to repo would be helpful.

The file needs to be under `.github` folder 
```
.github/release-drafter.yml
```

**Comment by pratyushbansal** [comment]
Sorry its a private repo
Location of file is under .github folder
and release-management.yml is in .github/workflows folder

Can it be related to branch?
I am adding this functionality to a separate branch ordering_intial_master and not on master

**Comment by pratyushbansal** [comment]
Hi @casz ,
Please help me out here

**Comment by casz** [comment]
I'd remove the `branches` section in the release-drafter.yml and in the workflow.yml I'd revert it to do it on master.

Then see what happens.

other then that I cannot really help, as the repo is private.

**Comment by TimonVS** [comment]
Like @casz suggests, you should probably remove the `branches` option from `release-drafter.yml`. It's not clear from the documentation but I'm pretty sure this option is meant to be used with the GitHub App version only, with GitHub Actions you can define the branches to listen for in the workflow definition (as you did already).

**Comment by pratyushbansal** [comment]
Hi, It started working after I added the yml file in the master branch.
Thanks for the help. Closing the issue
