### ISSUE TITLE
Release drafter tracks all PR and `branches` config is not applying

### ISSUE THREAD

**Issue by niveathika** [toolmantim/release-drafter#329]
I have been testing release-drafter today, and I have to say it's awesome. 

One issue I faced was it seems release drafter is tracking all PRs, I just needed it to track PRs to master branch. I tried the `branches` config too, However, it seems to not work.

Config, https://github.com/niveathika/test-project/blob/master/.github/release-drafter.yml

![Screenshot from 2019-11-20 19-39-37](https://user-images.githubusercontent.com/27669465/69245817-8cffd880-0bcd-11ea-90d1-24733ca0a28c.png)

As you can see PR https://github.com/niveathika/test-project/pull/11 was not to the master branch it seems it's not ignored.

**Comment by casz** [comment]
It's included in the commit history on master branch, hence this PR should be included in the release draft.

**Comment by niveathika** [comment]
Oh, I see. Thank you it's sorted! :)
