### ISSUE TITLE
Are Conventional Commits Supported?

### ISSUE THREAD

**Issue by Mike-EEE** [toolmantim/release-drafter#331]
I just setup our repo with this app, thank you for making it. 👍

One thing I noticed, however, is that it seems conventional commit messages retain their conventions:

![](https://i.imgur.com/wu8248C.png)

Perhaps I am doing something wrong?  I'm learning a lot here lately, so could be overlooking something obvious.

Ideally, it would be great to have the messages captured to have those scrubbed for human readability.

Thank you for any assistance you can provide!

**Comment by TimonVS** [comment]
It's not supported by Release Drafter out of the box. Not an ideal solution, but maybe you can do this with the [replacers functionality](https://github.com/toolmantim/release-drafter#replacers)?

**Comment by Mike-EEE** [comment]
Turns out that this is OK!  I was drinking from the firehose there for a bit. 😆  The PR Labeler and Create Issue Branch _appeared_ to use CC ([as you know](https://github.com/TimonVS/pr-labeler-action/issues/28) 😁), but you can configure them to use your own labels and any convention you want, really. 👍

Thank you for your reply and suggestion!
