### ISSUE TITLE
Environment variable for all contributors

### ISSUE THREAD

**Issue by bkeepers** [toolmantim/release-drafter#53]
Thanks for this awesome app! We just installed it and are going to start using it on the @probot org.

It'd be cool if the template included a string of all the people who contributed changes for a release so we could give them a special shoutout. I'm imagining adding this to our template:

> Special thanks to everyone who contributed to this release: $CONTRIBUTORS

**Comment by toolmantim** [comment]
Great idea! Just to check, that’d probably be the committer and author of every commit yeah, in alphabetical order?

**Comment by toolmantim** [comment]
Oh, and I forgot to say: that’s great to hear you’re going to be using it for Probot releases 🙌🏼❤️

**Comment by bkeepers** [comment]
> Great idea! Just to check, that’d probably be the committer and author of every commit yeah, in alphabetical order?

I would be ok if it was just the Pull Request authors.
