### ISSUE TITLE
Attribute changes to the original author

### ISSUE THREAD

**Issue by jeanregisser** [toolmantim/release-drafter#7]
Hi,

Great tool!
I tested it on one of my repo:

<img width="669" alt="screen shot 2018-07-10 at 09 03 09" src="https://user-images.githubusercontent.com/57791/42494320-3ce15418-8420-11e8-82a3-28b948ecf6fe.png">

Would it be possible to attribute the changes to the original author instead of the person who merged the PR?

Thanks

**Comment by toolmantim** [comment]
It's a good question, and one I raised myself with the GitHub peeps here:
https://twitter.com/toolmantim/status/1015762564955795456

Unfortunately there's no GitHub API to do it at the moment. But we'll leave this here, in case we find a solution at some point.

**Comment by jeanregisser** [comment]
Ah there's been a slight misunderstanding, my original question was about the fact that the release notes contain the github handle of the person who merged the PR:

> - Fix warnings when used in react-native-web (#122) @jeanregisser`

I wanted to know if the notes could instead mention the original author of the PR, in this case it should be:

> - Fix warnings when used in react-native-web (#122) @msand`

**Comment by toolmantim** [comment]
Ah! I understand. Yep, that’s a bug that needs fixing.

**Comment by toolmantim** [comment]
Fixed in #15
