### ISSUE TITLE
Squash & Merge PRs

### ISSUE THREAD

**Issue by balloob** [toolmantim/release-drafter#8]
I always use squash & merge when merging PRs. Just realized that this doesn't work with release-drafter. My change log looks like this:

![image](https://user-images.githubusercontent.com/1444314/42502626-e28d249e-8436-11e8-8a95-69268f24d38a.png)

Looking at the code, merge PRs are matched on "Merge pull request #" https://github.com/toolmantim/release-drafter/blob/e24d69800ca69614e821cf642097dd82e5206cd3/lib/commits.js#L23

Could this be updated to also match commits generated by squash & merge?

For example, `(\(#\d+\))$|Merge pull request #\d+` ([link](https://regex101.com/r/jc5wh2/2)):

![image](https://user-images.githubusercontent.com/1444314/42503134-2f188186-8438-11e8-997d-facfabcd555f.png)

**Comment by toolmantim** [comment]
Ah, good catch. Sorry you were hit by this bug, and thanks for the detailed report (with regex!). I'll get this fixed.

**Comment by toolmantim** [comment]
Fixed in #15
