### ISSUE TITLE
Support non-semver releases

### ISSUE THREAD

**Issue by toolmantim** [toolmantim/release-drafter#9]
Currently if you try to use Release Drafter on a repo that has non-semver compatible release names, it throws `Error: Invalid argument not valid semver` when [compare-versions is used](https://github.com/toolmantim/release-drafter/blob/master/lib/releases.js#L11).

We should perhaps just compare the dates of the two releases in this case, and assume the more recent release is greater?

**Comment by toolmantim** [comment]
@balloob this is why it's currently not working on https://github.com/home-assistant/home-assistant-polymer/releases

**Comment by balloob** [comment]
Maybe it could be an option ? `semver: false`. I can see how for projects with semver that have multiple active releases (like Node, example `6.X` and `8.X`), just picking the last one will not work.

**Comment by toolmantim** [comment]
Ah, multiple release tracks might be something else altogether though, but still a neat feature. For Node, right now it works but it'd only track the v10 releases, because it just asks "what's merged to master since the release with the highest semver version number?"

I'll get non-semver releases working to start. Multiple release paths can come later when people need.

**Comment by toolmantim** [comment]
Fixed in #15
