### ISSUE TITLE
Automatically name new draft releases according to semver

### ISSUE THREAD

**Issue by rnorth** [toolmantim/release-drafter#91]
Firstly thanks for creating this - I've used it in a couple of places and found it very helpful!

I'm wondering if you would accept a contribution for an opt-in feature to automatically name new draft releases. What I would like is for each new release to be `Last Release + 0.0.1`. My goal is to make it really easy to make a new patch release (as our most common release type), so that 'working out the next patch version number' becomes a mental no-op, as performing the release can be just a case of hitting the publish button.

Obviously there will be times when it's more appropriate to increment the major or minor version, but this would be easily done manually with no additional mental overhead from now.

How does this sound as a potential new feature?

**Comment by toolmantim** [comment]
Sounds great, I’ve pondered something similar. Would happily accept this as an option!

Over time I imagine we could add some smarts ala https://github.com/semantic-release/semantic-release for figuring out the new version number based on commits and/or labels.

**Comment by toolmantim** [comment]
Let me know if you need any help any way @rnorth 😊

**Comment by rnorth** [comment]
Thinking about this, I'm inclined to:

* introduce some new template variables (e.g. `NEXT_PATCH_VERSION`, `NEXT_MINOR_VERSION`, `NEXT_MAJOR_VERSION`)

* add two templatable fields to `.github/release-drafter.yml`: `defaultReleaseName` and `defaultReleaseTag`

This way, for our simple use case I can add to our config:
```yaml
defaultReleaseName: "$NEXT_PATCH_VERSION"
defaultReleaseTag:  "$NEXT_PATCH_VERSION"
```

but people with more interesting naming conventions, like a `v` prefix on their tags, could do this:
```yaml
defaultReleaseName: "$NEXT_PATCH_VERSION"
defaultReleaseTag:  "v$NEXT_PATCH_VERSION"   # note the v prefix here
```

Additionally, this would mean that these are available in the template, allowing things like this (if desired):

```yaml
template: |
  ## How to install

  Add this maven dependency:
  ``
  <dependency>
    <groupId>blah</groupId>
    <artifactId>blahblah</artifactId>
    <version>$NEXT_PATCH_VERSION</version>
  </dependency>
  ``
  ...

  ## What’s Changed

  $CHANGES
```

**Comment by toolmantim** [comment]
Nice! That's an even better idea. I can see myself personally using this is a default:

```yams
defaultReleaseName: "$NEXT_PATCH_VERSION"
defaultReleaseTag:  "v$NEXT_PATCH_VERSION"
``
